#Dockerfile.dev - for local development; for production - Dockerfile
FROM node:alpine

WORKDIR /usr/app

COPY package.json .

RUN npm install

# not required if we are specifying volumes in docker-compose; good to have if we event want to switch to this dockerfile, production?
COPY . .

CMD ["npm", "start"]
